baseurl = "https://roadster.pages.dev"
title = "Roadster"
languageCode = "en-us"
# paginate = "10" # DEPRECATED! Use pagination.pagerSize below
theme = "roadster"
# disqusShortname = "" # DEPRECATED! Use .Services.Disqus.Shortname below
# googleAnalytics = "" # DEPRECATED! Use .Services.googleAnalytics.ID below

# Configure Pagination. See https://gohugo.io/templates/pagination/#configuration
[pagination]
  pagerSize = 10 # (int) The number of pages per pager. Default is 10

[services]
  [services.googleAnalytics]
    id = 'G-MEASUREMENT_ID'  # Enable Google Analytics by entering your tracking id
  [services.disqus]
    shortname = 'your-disqus-shortname' # Enable Disqus by entering your Disqus shortname

# Goldmark renders raw HTML mixed within the Markdown
[markup.goldmark.renderer]
  unsafe = true # N.B. This is unsafe unless the content is under your control.  Set to false if you don't mix HTML with markdown.

[Params]
  description = "John Doe's Personal blog about everything" # Description of your site
  opengraph = true
  twitter_cards = false
  readmore = false # Show "Read more" button in list if true
  authorbox = true
  pager = true
  post_meta = ["date", "categories"] # Order of post meta information
  mainSections = ["post", "docs"]
  CustomHeadHTML = "" # Add custom HTML in the <head> 

[params.author]
  name = "John Doe"
  bio = "John Doe's true identity is unknown. Maybe he is a successful blogger or writer. Nobody knows it."
  avatar = "img/avatar.png"

[Params.logo]
  subtitle = "Streamlined design, enhanced functionality" # Logo subtitle

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
